version: 2
project_name: orbit-cli

before:
  hooks: []

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w -X github.com/svector-corporation/orbit-cli/internal/version.Version={{.Version}}
    main: ./main.go

archives:
  - format: tar.gz
    name_template: >-
      orbit-cli-
      {{- if eq .Os "darwin" }}mac-
      {{- else if eq .Os "windows" }}windows-
      {{- else if eq .Os "linux" }}linux-{{ end }}
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "#86" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    format_overrides:
      - goos: windows
        format: zip

checksum:
  name_template: "checksums.txt"

snapshot:
  name_template: "0.0.0-{{ .Timestamp }}"

aurs:
  - name: orbit-cli
    homepage: "https://github.com/svector-corporation/orbit-cli"
    description: "orbit-cli — the official SVECTOR command-line interface"
    maintainers:
      - "svector <support@svector.co.in>"
    license: "MIT"
    private_key: "{{ .Env.AUR_KEY }}"
    git_url: "ssh://aur@aur.archlinux.org/orbit-cli-bin.git"
    provides:
      - orbit-cli
    conflicts:
      - orbit-cli
    package: |-
      install -Dm755 ./orbit-cli "${pkgdir}/usr/bin/orbit-cli"

brews:
  - repository:
      owner: svector
      name: homebrew-tap

nfpms:
  - maintainer: svector
    description: orbit-cli — the official CLI tool by SVECTOR
    formats:
      - deb
      - rpm
    file_name_template: >-
      {{ .ProjectName }}-
      {{- if eq .Os "darwin" }}mac
      {{- else }}{{ .Os }}{{ end }}-{{ .Arch }}

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^doc:"
      - "^test:"
      - "^ci:"
      - "^ignore:"
      - "^example:"
      - "^wip:"
